BUNDLE_NAME = Flashlight
Flashlight_FILES = Switch.x
Flashlight_FRAMEWORKS = AVFoundation
Flashlight_LIBRARIES = flipswitch
Flashlight_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
