BUNDLE_NAME = Respring
Respring_FILES = Switch.x
Respring_FRAMEWORKS = UIKit
Respring_LIBRARIES = flipswitch
Respring_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
