BUNDLE_NAME = Settings
Settings_FILES = Switch.x
Settings_FRAMEWORKS = UIKit
Settings_LIBRARIES = flipswitch
Settings_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
