BUNDLE_NAME = VPN
VPN_FILES = Switch.x
VPN_FRAMEWORKS = UIKit
VPN_PRIVATE_FRAMEWORKS = Preferences
VPN_LIBRARIES = flipswitch
VPN_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
