BUNDLE_NAME = 3G
3G_FILES = Switch.x
3G_FRAMEWORKS = UIKit CoreTelephony
3G_PRIVATE_FRAMEWORKS = GraphicsServices
3G_LIBRARIES = flipswitch
3G_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
