BUNDLE_NAME = Ringer
Ringer_FILES = Switch.x
Ringer_FRAMEWORKS = UIKit
Ringer_LIBRARIES = flipswitch
Ringer_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
