BUNDLE_NAME = Bluetooth
Bluetooth_FILES = Switch.x
Bluetooth_FRAMEWORKS = UIKit
Bluetooth_LIBRARIES = flipswitch
Bluetooth_PRIVATE_FRAMEWORKS = BluetoothManager
Bluetooth_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
