BUNDLE_NAME = Data
Data_FILES = Switch.x
Data_FRAMEWORKS = UIKit CoreTelephony
Data_PRIVATE_FRAMEWORKS = GraphicsServices
Data_LIBRARIES = flipswitch
Data_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
