include @@THEOS@@/makefiles/common.mk

BUNDLE_NAME = @@PROJECTNAME@@
@@PROJECTNAME@@_FILES = Switch.x
@@PROJECTNAME@@_FRAMEWORKS = UIKit
@@PROJECTNAME@@_LIBRARIES = flipswitch
@@PROJECTNAME@@_INSTALL_PATH = /Library/Switches

include $(THEOS_MAKE_PATH)/bundle.mk