BUNDLE_NAME = Wifi
Wifi_FILES = Switch.x
Wifi_FRAMEWORKS = UIKit
Wifi_LIBRARIES = flipswitch
Wifi_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
