BUNDLE_NAME = WifiProxy
WifiProxy_FILES = Switch.x
WifiProxy_FRAMEWORKS = UIKit SystemConfiguration
WifiProxy_LIBRARIES = flipswitch
WifiProxy_INSTALL_PATH = /Library/Switches

ADDITIONAL_CFLAGS = -I../../
ADDITIONAL_LDFLAGS = -L../../$(THEOS_OBJ_DIR_NAME)

include $(THEOS)/makefiles/common.mk
include $(THEOS_MAKE_PATH)/library.mk
include $(THEOS_MAKE_PATH)/bundle.mk
